## Climate Change

Przykład na zbiorze: https://www.kaggle.com/datasets/berkeleyearth/climate-change-earth-surface-temperature-data?datasetId=29&searchQuery=seas&select=GlobalLandTemperaturesByCountry.csv

Import bibliotek

In [1]:
import pandas as pd
import plotly.express as px

In [2]:
df = pd.read_csv('GlobalLandTemperaturesByCountry.csv',sep=',', encoding='utf8',decimal='.')
df.head()

           dt  AverageTemperature  AverageTemperatureUncertainty Country
0  1743-11-01               4.384                          2.294   Åland
1  1743-12-01                 NaN                            NaN   Åland
2  1744-01-01                 NaN                            NaN   Åland
3  1744-02-01                 NaN                            NaN   Åland
4  1744-03-01                 NaN                            NaN   Åland

In [3]:
df.describe()

       AverageTemperature  AverageTemperatureUncertainty
count       544811.000000                  545550.000000
mean            17.193354                       1.019057
std             10.953966                       1.201930
min            -37.658000                       0.052000
25%             10.025000                       0.323000
50%             20.901000                       0.571000
75%             25.814000                       1.206000
max             38.842000                      15.003000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 577462 entries, 0 to 577461
Data columns (total 4 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   dt                             577462 non-null  object
 1   AverageTemperature             544811 non-null  float64
 2   AverageTemperatureUncertainty  545550 non-null  float64
 3   Country                        577462 non-null  object
dtypes: float64(2), object(2)
memory usage: 17.6+ MB

In [5]:
df.isnull().sum() 
# df['Country'].unique()

dt                                   0
AverageTemperature               32651
AverageTemperatureUncertainty    31912
Country                              0
dtype: int64

In [6]:
lista_panstw = ['Poland', 'Germany','Czech Republic','United Kingdom', 'France', 'Italy','Canada', 'United States', 'China', 'India', 'Japan', 'Australia', 'Brazil', 'Russia', 'South Africa']
wybrane_kraje = df[df['Country'].isin(lista_panstw)].copy().reset_index()
wybrane_kraje.head()

,index,dt,AverageTemperature,AverageTemperatureUncertainty,Country
0,34816,1852-07-01,14.116,1.530,Australia
1,34817,1852-08-01,15.330,1.400,Australia
2,34818,1852-09-01,18.740,1.446,Australia
3,34819,1852-10-01,21.984,1.493,Australia
4,34820,1852-11-01,24.073,1.466,Australia

In [7]:
wybrane_kraje["Date"] = pd.to_datetime(wybrane_kraje["dt"])
wybrane_kraje["Year"] = wybrane_kraje["Date"].dt.year
wybrane_kraje["Month"] = wybrane_kraje["Date"].dt.month
wybrane_kraje["Day"] = wybrane_kraje["Date"].dt.day
# wybrane_kraje.head()
wybrane_kraje.dropna(subset=['AverageTemperature'], inplace=True)
wybrane_kraje.drop(['dt'], inplace=True, axis=1)
wybrane_kraje.head()

,index,AverageTemperature,AverageTemperatureUncertainty,Country,Date,Year,Month,Day
0,34816,14.116,1.530,Australia,1852-07-01,1852,7,1
1,34817,15.330,1.400,Australia,1852-08-01,1852,8,1
2,34818,18.740,1.446,Australia,1852-09-01,1852,9,1
3,34819,21.984,1.493,Australia,1852-10-01,1852,10,1
4,34820,24.073,1.466,Australia,1852-11-01,1852,11,1

In [8]:
tmp = wybrane_kraje.groupby(['Year', 'Country'])['AverageTemperature'].mean().reset_index()
tmp = tmp.sort_values('AverageTemperature', ascending=True)
tmp = tmp.sort_values('Year', ascending=True)
tmp

      Year         Country  AverageTemperature
1     1743          France           10.203000
4     1743          Poland            3.937000
2     1743         Germany            5.468000
0     1743  Czech Republic            4.167000
3     1743           Italy            9.538000
...    ...             ...                 ...
3293  2013  Czech Republic            9.281000
3297  2013           Italy           14.165000
3294  2013          France           13.584625
3291  2013          Canada           -1.640667
3301  2013    South Africa           17.325375

[3304 rows x 3 columns]

## Wizualizacja globu za pomocą Plotly

In [9]:
fig = px.choropleth(tmp,locations='Country', locationmode='country names', 
                    color='AverageTemperature', color_continuous_scale='temps',
                    hover_name='Country', title='Średnia temperatura w wybranych krajach',
                    animation_frame='Year', animation_group='Country',
                    height=600, width=1000)

fig.update_layout(title_x=0.5, title_y=0.95, title_font_size=20)

fig.update_geos(projection_type="orthographic", showocean=True, oceancolor="LightBlue",
                showland=True,showlakes=False, lakecolor="LightBlue")

fig.show()