## Climate Change

Przykład na zbiorze: https://www.kaggle.com/datasets/berkeleyearth/climate-change-earth-surface-temperature-data?datasetId=29&searchQuery=seas&select=GlobalLandTemperaturesByCountry.csv

Import bibliotek

In [2]:
import pandas as pd
import plotly.express as px

In [3]:
df = pd.read_csv('GlobalLandTemperaturesByCountry.csv',sep=',', encoding='utf8',decimal='.')
df.head()

           dt  AverageTemperature  AverageTemperatureUncertainty Country
0  1743-11-01               4.384                          2.294   Åland
1  1743-12-01                 NaN                            NaN   Åland
2  1744-01-01                 NaN                            NaN   Åland
3  1744-02-01                 NaN                            NaN   Åland
4  1744-03-01                 NaN                            NaN   Åland

In [4]:
df.describe()

       AverageTemperature  AverageTemperatureUncertainty
count       544811.000000                  545550.000000
mean            17.193354                       1.019057
std             10.953966                       1.201930
min            -37.658000                       0.052000
25%             10.025000                       0.323000
50%             20.901000                       0.571000
75%             25.814000                       1.206000
max             38.842000                      15.003000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 577462 entries, 0 to 577461
Data columns (total 4 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   dt                             577462 non-null  object
 1   AverageTemperature             544811 non-null  float64
 2   AverageTemperatureUncertainty  545550 non-null  float64
 3   Country                        577462 non-null  object
dtypes: float64(2), object(2)
memory usage: 17.6+ MB

In [6]:
df.isnull().sum()

dt                                   0
AverageTemperature               32651
AverageTemperatureUncertainty    31912
Country                              0
dtype: int64

In [7]:
lista_panstw = ['Poland', 'Germany', 'United Kingdom', 'France', 'Italy','Canada', 'United States', 'China', 'India', 'Japan', 'Australia', 'Brazil', 'Russia', 'South Africa']
wybrane_kraje = df[df['Country'].isin(lista_panstw)]
wybrane_kraje.head()

,dt,AverageTemperature,AverageTemperatureUncertainty,Country
34816,1852-07-01,14.116,1.530,Australia
34817,1852-08-01,15.330,1.400,Australia
34818,1852-09-01,18.740,1.446,Australia
34819,1852-10-01,21.984,1.493,Australia
34820,1852-11-01,24.073,1.466,Australia

In [8]:
wybrane_kraje = wybrane_kraje.copy()
wybrane_kraje["Date"] = pd.to_datetime(wybrane_kraje["dt"])
wybrane_kraje["Rok"] = wybrane_kraje["Date"].dt.year
wybrane_kraje["Miesiac"] = wybrane_kraje["Date"].dt.month
wybrane_kraje["Dzien"] = wybrane_kraje["Date"].dt.day
# wybrane_kraje.head()
wybrane_kraje.dropna(subset=['AverageTemperature'], inplace=True)

In [9]:
tmp = wybrane_kraje.groupby(['Country', 'Rok'])['AverageTemperature'].mean().reset_index()
tmp = tmp.sort_values('AverageTemperature', ascending=True)
tmp = tmp.sort_values('Rok', ascending=True)

In [10]:
fig = px.choropleth(tmp,locations='Country',locationmode='country names', 
                    color='AverageTemperature',
                    hover_name='Country', title='Średnia temperatura w wybranych krajach',
                    animation_frame='Rok',animation_group='Country')

fig.update_geos(projection_type="orthographic", showocean=True, oceancolor="LightBlue",
                showland=True, landcolor="LightGreen", showlakes=True, lakecolor="LightBlue")
fig.update_layout(height = 600, width = 1000, title_x=0.5, margin={"r":0,"t":50,"l":0,"b":0})
fig.show()